### ISSUE TITLE
[panic] when use an non-exist  user for data resource

### ISSUE THREAD

**Issue by chensunny** [mrparkers/terraform-provider-keycloak#449]
```
data "keycloak_realm" "realm" {
   realm  = "master"
}

data "keycloak_user" "users" {
  for_each     = toset(["bob1@domain.com","bob2@domain.com","bob3@domain.com"])
  realm_id     = data.keycloak_realm.realm.id
  username     = each.key
}

```

**when bob3@domain.com  is non-exist**

```
2020-12-22T19:07:47.694+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: 2020/12/22 19:07:47 [DEBUG] Response: 200 OK
2020-12-22T19:07:47.698+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: panic: runtime error: invalid memory address or nil pointer dereference
2020-12-22T19:07:47.698+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: [signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x1a796ba]
2020-12-22T19:07:47.698+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: 
2020-12-22T19:07:47.698+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: goroutine 119 [running]:
2020-12-22T19:07:47.698+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: github.com/mrparkers/terraform-provider-keycloak/provider.mapFromUserToData(0xc0000f8800, 0x0)
2020-12-22T19:07:47.698+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: 	github.com/mrparkers/terraform-provider-keycloak/provider/resource_keycloak_user.go:160 +0x3a
2020-12-22T19:07:47.699+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: github.com/mrparkers/terraform-provider-keycloak/provider.dataSourceKeycloakUserRead(0xc0000f8800, 0x1cec500, 0xc0003013e0, 0x272b730, 0x1d42dd8)
2020-12-22T19:07:47.699+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: 	github.com/mrparkers/terraform-provider-keycloak/provider/data_source_keycloak_user.go:70 +0x141
2020-12-22T19:07:47.699+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00014ac60, 0x1f6a800, 0xc0001e3140, 0xc0000f8800, 0x1cec500, 0xc0003013e0, 0x0, 0x0, 0x0)
2020-12-22T19:07:47.699+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.2-0.20200817173939-b72757e734f6/helper/schema/resource.go:281 +0x88
2020-12-22T19:07:47.699+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc00014ac60, 0x1f6a800, 0xc0001e3140, 0xc0002af880, 0x1cec500, 0xc0003013e0, 0xc0003013e0, 0xc0002af880, 0x0, 0x0)
2020-12-22T19:07:47.699+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.2-0.20200817173939-b72757e734f6/helper/schema/resource.go:489 +0xff
2020-12-22T19:07:47.699+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: github.com/hashicorp/terraform-plugin-sdk/v2/internal/helper/plugin.(*GRPCProviderServer).ReadDataSource(0xc000795080, 0x1f6a800, 0xc0001e3140, 0xc0001e3100, 0xc000795080, 0xc000795090, 0x1d42dc8)
2020-12-22T19:07:47.699+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.2-0.20200817173939-b72757e734f6/internal/helper/plugin/grpc_provider.go:1102 +0x4c5
2020-12-22T19:07:47.699+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: github.com/hashicorp/terraform-plugin-sdk/v2/internal/tfplugin5._Provider_ReadDataSource_Handler.func1(0x1f6a800, 0xc0001e3140, 0x1c80ac0, 0xc0001e3100, 0xc0001e3140, 0x1bd5cc0, 0xc0005a4401, 0xc0002af6a0)
2020-12-22T19:07:47.699+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.2-0.20200817173939-b72757e734f6/internal/tfplugin5/tfplugin5.pb.go:3348 +0x86
2020-12-22T19:07:47.700+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: github.com/hashicorp/terraform-plugin-sdk/v2/plugin.Serve.func3.1(0x1f6a8c0, 0xc0001ab710, 0x1c80ac0, 0xc0001e3100, 0xc0002af680, 0xc0002af6a0, 0xc0005b1ba0, 0x11bde78, 0x1c5e0e0, 0xc0001ab710)
2020-12-22T19:07:47.700+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.2-0.20200817173939-b72757e734f6/plugin/serve.go:76 +0x87
2020-12-22T19:07:47.700+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: github.com/hashicorp/terraform-plugin-sdk/v2/internal/tfplugin5._Provider_ReadDataSource_Handler(0x1cb4140, 0xc000795080, 0x1f6a8c0, 0xc0001ab710, 0xc0005a44e0, 0xc0007bdc60, 0x1f6a8c0, 0xc0001ab710, 0xc000196600, 0xb6)
2020-12-22T19:07:47.700+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.2-0.20200817173939-b72757e734f6/internal/tfplugin5/tfplugin5.pb.go:3350 +0x14b
2020-12-22T19:07:47.700+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000339500, 0x1f764a0, 0xc000682900, 0xc000106800, 0xc000215290, 0x26f2650, 0x0, 0x0, 0x0)
2020-12-22T19:07:47.700+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: 	google.golang.org/grpc@v1.30.0/server.go:1171 +0x50a
2020-12-22T19:07:47.700+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: google.golang.org/grpc.(*Server).handleStream(0xc000339500, 0x1f764a0, 0xc000682900, 0xc000106800, 0x0)
2020-12-22T19:07:47.700+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: 	google.golang.org/grpc@v1.30.0/server.go:1494 +0xccd
2020-12-22T19:07:47.700+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000b4220, 0xc000339500, 0x1f764a0, 0xc000682900, 0xc000106800)
2020-12-22T19:07:47.700+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: 	google.golang.org/grpc@v1.30.0/server.go:834 +0xa1
2020-12-22T19:07:47.700+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-12-22T19:07:47.700+0800 [DEBUG] plugin.terraform-provider-keycloak_v2.0.0: 	google.golang.org/grpc@v1.30.0/server.go:832 +0x204

```

**Comment by mrparkers** [comment]
thanks for reporting this, I've opened a PR to fix it.
