### ISSUE TITLE
Terraform Crashes when User Data Block References Username that does not exist

### ISSUE THREAD

**Issue by timothymathison** [mrparkers/terraform-provider-keycloak#480]
## Description

The `GetUserByUsername` method does not throw an error when a `user` lookup by `username` does not find anything.
https://github.com/mrparkers/terraform-provider-keycloak/blob/490a46b25603fbfcf79dde6eb3e9afb08bf0441b/keycloak/user.go#L160

This causes a `data.keycloak_user` block which mentions a non-existent `username` to crash terraform due to a `nil` reference error when `dataSourceKeycloakUserRead` attempts to call `mapUserToData`:
https://github.com/mrparkers/terraform-provider-keycloak/blob/490a46b25603fbfcf79dde6eb3e9afb08bf0441b/provider/data_source_keycloak_user.go#L74
I believe the the error occures when `mapUserToData` attempts to dereference the `user` object while accessing the `FederatedIdentities` property:
https://github.com/mrparkers/terraform-provider-keycloak/blob/490a46b25603fbfcf79dde6eb3e9afb08bf0441b/provider/resource_keycloak_user.go#L160

## Error Output

```
data.keycloak_user.users["foo"]: Refreshing state... [id=<redacted>]


Error: rpc error: code = Canceled desc = context canceled




Error: rpc error: code = Canceled desc = context canceled




Error: rpc error: code = Canceled desc = context canceled




Error: rpc error: code = Canceled desc = context canceled




Error: rpc error: code = Unavailable desc = transport is closing


.

.

.


panic: runtime error: invalid memory address or nil pointer dereference

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: [signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0xe7fbfa]

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: 

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: goroutine 325 [running]:

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: github.com/mrparkers/terraform-provider-keycloak/provider.mapFromUserToData(0xc00010ff00, 0x0)

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: 	/Users/<user>/go/src/github.com/mrparkers/terraform-provider-keycloak/provider/resource_keycloak_user.go:160 +0x3a

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: github.com/mrparkers/terraform-provider-keycloak/provider.dataSourceKeycloakUserRead(0xc00010ff00, 0x10f6740, 0xc0007d2b90, 0x1b41b00, 0x114d780)

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: 	/Users/<user>/go/src/github.com/mrparkers/terraform-provider-keycloak/provider/data_source_keycloak_user.go:70 +0x141

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00058d080, 0x1375400, 0xc00059d700, 0xc00010ff00, 0x10f6740, 0xc0007d2b90, 0x0, 0x0, 0x0)

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: 	/Users/<user>/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.2-0.20200817173939-b72757e734f6/helper/schema/resource.go:281 +0x88

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc00058d080, 0x1375400, 0xc00059d700, 0xc000e252e0, 0x10f6740, 0xc0007d2b90, 0xc0007d2b90, 0xc000e252e0, 0x0, 0x0)

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: 	/Users/<user>/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.2-0.20200817173939-b72757e734f6/helper/schema/resource.go:489 +0xff

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: github.com/hashicorp/terraform-plugin-sdk/v2/internal/helper/plugin.(*GRPCProviderServer).ReadDataSource(0xc0006283a0, 0x1375400, 0xc00059d700, 0xc00059d680, 0xc0006283a0, 0xc0006283b0, 0x114d770)

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: 	/Users/<user>/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.2-0.20200817173939-b72757e734f6/internal/helper/plugin/grpc_provider.go:1102 +0x4c5

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: github.com/hashicorp/terraform-plugin-sdk/v2/internal/tfplugin5._Provider_ReadDataSource_Handler.func1(0x1375400, 0xc00059d700, 0x108ace0, 0xc00059d680, 0xc00059d700, 0xfdf820, 0xc00007cf01, 0xc000e25100)

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: 	/Users/<user>/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.2-0.20200817173939-b72757e734f6/internal/tfplugin5/tfplugin5.pb.go:3348 +0x86

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: github.com/hashicorp/terraform-plugin-sdk/v2/plugin.Serve.func3.1(0x13754c0, 0xc00001dc50, 0x108ace0, 0xc00059d680, 0xc000e250e0, 0xc000e25100, 0xc0007bbba0, 0x5c17f8, 0x1068280, 0xc00001dc50)

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: 	/Users/<user>/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.2-0.20200817173939-b72757e734f6/plugin/serve.go:76 +0x87

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: github.com/hashicorp/terraform-plugin-sdk/v2/internal/tfplugin5._Provider_ReadDataSource_Handler(0x10bde80, 0xc0006283a0, 0x13754c0, 0xc00001dc50, 0xc00007cf60, 0xc0000bdd20, 0x13754c0, 0xc00001dc50, 0xc0008d80f0, 0xe1)

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: 	/Users/<user>/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.2-0.20200817173939-b72757e734f6/internal/tfplugin5/tfplugin5.pb.go:3350 +0x14b

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000210000, 0x1380e40, 0xc000316d80, 0xc000122b00, 0xc0001a2330, 0x1b085d0, 0x0, 0x0, 0x0)

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: 	/Users/<user>/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1171 +0x50a

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: google.golang.org/grpc.(*Server).handleStream(0xc000210000, 0x1380e40, 0xc000316d80, 0xc000122b00, 0x0)

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: 	/Users/<user>/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1494 +0xccd

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000626230, 0xc000210000, 0x1380e40, 0xc000316d80, 0xc000122b00)

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: 	/Users/<user>/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:834 +0xa1

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: created by google.golang.org/grpc.(*Server).serveStreams.func1

2021-02-04T19:24:21.262Z [DEBUG] plugin.terraform-provider-keycloak_2.0.1_linux_amd64: 	/Users/<user>/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:832 +0x204

.

.

.

2021/02/04 19:24:21 [TRACE] dag/walk: upstream of "github_repository_file.summary (expand)" errored, so skipping

2021/02/04 19:24:21 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hashicorp/github\"] (close)" errored, so skipping

2021/02/04 19:24:21 [TRACE] dag/walk: upstream of "root" errored, so skipping

2021/02/04 19:24:21 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info

2021/02/04 19:24:21 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock

2021-02-04T19:24:21.390Z [DEBUG] plugin: plugin exited

2021-02-04T19:24:21.396Z [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/hashicorp/github/4.0.1/linux_amd64/terraform-provider-github_v4.0.1_x4 pid=496

2021-02-04T19:24:21.396Z [DEBUG] plugin: plugin exited




!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!


Terraform crashed! This is always indicative of a bug within Terraform.

A crash log has been placed at "crash.log" relative to your current

working directory. It would be immensely helpful if you could please

report the crash with Terraform[1] so that we can fix this.


When reporting bugs, please include your terraform version. That

information is available on the first line of crash.log. You can also

get it by running 'terraform --version' on the command line.


SECURITY WARNING: the "crash.log" file that was created may contain 

sensitive information that must be redacted before it is safe to share 

on the issue tracker.


[1]: https://github.com/hashicorp/terraform/issues


!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

script returned exit code 1
```

## Expected Behavior

A human readable error should be printed in the terraform logs indicating that a user with that `username` does not exist.

**Comment by mrparkers** [comment]
Hey @timothymathison, can you try upgrading to [v2.2.0](https://github.com/mrparkers/terraform-provider-keycloak/blob/master/CHANGELOG.md#v220-january-23-2021)?  This was fixed in that release.  Give that a shot and let me know if you still have an issue.

Thanks!

**Comment by timothymathison** [comment]
> Hey @timothymathison, can you try upgrading to [v2.2.0](https://github.com/mrparkers/terraform-provider-keycloak/blob/master/CHANGELOG.md#v220-january-23-2021)? This was fixed in that release. Give that a shot and let me know if you still have an issue.
> 
> Thanks!

Ah, I missed that fix. We're using a forked version of the provider that doesn't have that yet. I will update our fork and try it.

**Comment by timothymathison** [comment]
Upgrading to `v2.2.0` fixed the issue. Thanks!
