### ISSUE TITLE
panic: interface conversion: interface {} is nil, not map[string]interface {}

### ISSUE THREAD

**Issue by Toilal** [mrparkers/terraform-provider-keycloak#666]
```
Stack trace from the terraform-provider-keycloak_v3.7.0 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 83 [running]:
github.com/mrparkers/terraform-provider-keycloak/provider.getRealmFromData(0xc00012a300, 0xc0000c03d0, 0xc0000c0340, 0xc000549698)
	github.com/mrparkers/terraform-provider-keycloak/provider/resource_keycloak_realm.go:724 +0x4c3f
github.com/mrparkers/terraform-provider-keycloak/provider.resourceKeycloakRealmCreate(0xc00012a300, 0xe11180, 0xc0003104e0, 0x5, 0xffffffffffffffff)
	github.com/mrparkers/terraform-provider-keycloak/provider/resource_keycloak_realm.go:1314 +0x47
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0004182a0, 0xf33a98, 0xc0002b8d80, 0xc00012a300, 0xe11180, 0xc0003104e0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:329 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0004182a0, 0xf33a98, 0xc0002b8d80, 0xc0006969c0, 0xc00012ba00, 0xe11180, 0xc0003104e0, 0x0, 0x0, 0x0, ...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000128540, 0xf33a98, 0xc0002b8d80, 0xc00062c690, 0xe1e1ed, 0x12, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xacf
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00012a380, 0xf33b40, 0xc0002b8d80, 0xc00030e0e0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x465
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xdd9f60, 0xc00012a380, 0xf33b40, 0xc0004f3ec0, 0xc000646d20, 0x0, 0xf33b40, 0xc0004f3ec0, 0xc000610000, 0xe62)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000144a80, 0xf3ac98, 0xc000603500, 0xc00060c000, 0xc0002fe600, 0x13f1580, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000144a80, 0xf3ac98, 0xc000603500, 0xc00060c000, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000120200, 0xc000144a80, 0xf3ac98, 0xc000603500, 0xc00060c000)
	google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-keycloak_v3.7.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by Toilal** [comment]
To reproduce the crash, setup the following realm resource :

```terraform
resource "keycloak_realm" "default" {
  realm   = "my-realm"

  smtp_server {
      host = "localhost"
      from = "no-reply@localhost"

      auth {
        username = ""
        password = ""
      }
  }
}
```

It should not crash because of empty username/password

**Comment by mrparkers** [comment]
Hi @Toilal, thanks for opening this issue. Unfortunately this is a bug within the terraform-plugin-sdk, so there's nothing I can do to fix this at the moment.

This was first discovered in #535, where I also posted a workaround you can use if you're trying to use a variable for SMTP username / password configuration that might sometimes be an empty string.

You can also see the bug report I made here: https://github.com/hashicorp/terraform-plugin-sdk/issues/216.
